import os

MAX_CONCURRENCY = int(os.getenv("MAX_CONCURRENCY", "1"))
REQUEST_TIMEOUT_S = int(os.getenv("REQUEST_TIMEOUT_S", "300"))
STREAM_REQUEST_TIMEOUT_S = int(os.getenv("STREAM_REQUEST_TIMEOUT_S", "1200"))
STREAM_SEGMENT_CHARS = int(os.getenv("STREAM_SEGMENT_CHARS", "420"))
MODEL_IDLE_TIMEOUT_S = int(os.getenv("MODEL_IDLE_TIMEOUT_S", "3600"))
